version: "3.8"

services:
  mongodb:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGODB_DATABASE: nestjs_db
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
